import smbus2

name = 'Gassensor'
SEN66_ADDRESS = 0x6B
bus = smbus2.SMBus(1)
command = [0x0021, 0x0202, 0x0300]  #(Starten,Status,Lesen)
errorcode=[12,11,9,7,6]  # CO2,PM,CO2,Gas,RH&T

def start_up(nummer):
    bus.write_i2c_block_data(SEN66_ADDRESS, command[0])
    status='ON'
    for x in errorcode:
        if get_bit(bus.read_i2c_block_data(SEN66_ADDRESS),x)==1:
         status='OFF'
         error = x
         break
    return name, status, error, SEN66_ADDRESS, nummer


def check_data():
    if bus.read_i2c_block_data(SEN66_ADDRESS,command[1])==True:
        return True
    else:
        return False

def read_measurement():
    try:
        # Lese 27 Bytes (z. B. 2 Byte CO2, 1 CRC, 2 Byte Temp, 1 CRC, 2 Byte RH, 1 CRC)
        data = bus.read_i2c_block_data(SEN66_ADDRESS, command[2], 27)

        def convert(high, low):
            return (high << 8) | low

        pm10_raw = convert(data[0], data[1])
        pm25_raw = convert(data[3], data[4])
        pm40_raw = convert(data[6], data[7])
        pm100_raw= convert(data[9], data[10])
        hum_raw = convert(data[12], data[13])
        temp_raw = convert(data[15], data[16])
        voc_raw = convert(data[18], data[19])
        nox_raw = convert(data[21], data[22])
        co2_raw = convert(data[24], data[25])

        # Werte je nach Datenblatt umrechnen
        pm10 = pm10_raw/10
        pm25 = pm25_raw/10
        pm40 = pm40_raw/10
        pm100 = pm100_raw/10
        humidity = hum_raw/100
        temperature = temp_raw/200
        voc = voc_raw/10
        nox = nox_raw/10
        co2 = co2_raw
        
        return pm10,pm25,pm40,pm100,humidity,temperature,voc,nox,co2
    
    except Exception as e:
        return None, None, None,None,None,None,None,None,None
    
def get_bit(register, bit_number):
  mask = 1 << bit_number  # Erstellt eine Bitmaske für das gewünschte Bit
  return (register & mask) >> bit_number




######################################

#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2025 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.1.2
# Product:       sen66
# Model-Version: 1.6.0
#

#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2025 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 1.1.2
# Product:       sen66
# Model-Version: 1.6.0
#

import argparse
import time
from sensirion_i2c_driver import LinuxI2cTransceiver, I2cConnection, CrcCalculator
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_sen66.device import Sen66Device

def init_sensor(i2c_port):
    """Initialisiert den Sensor und gibt das Sensorobjekt zurück."""
    i2c_transceiver = LinuxI2cTransceiver(i2c_port)
    channel = I2cChannel(
        I2cConnection(i2c_transceiver),
        slave_address=0x6B,
        crc=CrcCalculator(8, 0x31, 0xff, 0x0)
    )
    sensor = Sen66Device(channel)
    sensor.device_reset()
    time.sleep(1.2)
    serial_number = sensor.get_serial_number()
    print(f"Serial Number: {serial_number}")
    sensor.start_continuous_measurement()
    return sensor, i2c_transceiver

def read_measurements(sensor, interval_sec=5, count=100):
    """Liest Messwerte in einem Intervall aus."""
    try:
        # (
        #     mass_concentration_pm1p0,
        #     mass_concentration_pm2p5,
        #     mass_concentration_pm4p0,
        #     mass_concentration_pm10p0,
        #     humidity,
        #     temperature,
        #     voc_index,
        #     nox_index,
        #     co2
        # ) = sensor.read_measured_values()
        # print(f"PM1.0: {mass_concentration_pm1p0}, "
        #         f"PM2.5: {mass_concentration_pm2p5}, "
        #         f"PM4.0: {mass_concentration_pm4p0}, "
        #         f"PM10.0: {mass_concentration_pm10p0}, "
        #         f"Humidity: {humidity}, "
        #         f"Temperature: {temperature}, "
        #         f"VOC Index: {voc_index}, "
        #         f"NOx Index: {nox_index}, "
        #         f"CO2: {co2}")
        return sensor.read_measured_values()
    except KeyboardInterrupt:
        print("Measurement stopped by user.")
    except Exception as e:
        print(f"Error during measurement: {e}")

def stop_sensor(sensor, i2c_transceiver):
    """Stoppt die Messung und schließt die Verbindung."""
    sensor.stop_measurement()
    i2c_transceiver.close()
    print("Measurement stopped and connection closed.")

def data_printout(data):
    """Gibt die Messdaten in einem lesbaren Format aus."""
    if data is None:
        print("No data available.")
        return
    pm10, pm25, pm40, pm100, humidity, temperature, voc, nox, co2 = data
    print(f"PM10: {pm10}, PM2.5: {pm25}, PM4.0: {pm40}, PM100: {pm100}, "
          f"Humidity: {humidity}, Temperature: {temperature}, "
          f"VOC Index: {voc}, NOx Index: {nox}, CO2: {co2}")

# def get_args():
#     parser = argparse.ArgumentParser()
#     parser.add_argument('--i2c-port', '-p', default='/dev/i2c-1')
#     args = parser.parse_args()
#     return args

if __name__ == "__main__":
    from software.utils import get_args
    args = get_args()
    sensor, i2c_transceiver = init_sensor(args.i2c_port)
    print("Starting measurements...")
    print("60 secounds startup time for the sensor, please wait...")
    time.sleep(60)
    # for i in range(100):
    i = 0
    while True:
        try:
            data = read_measurements(sensor)
            print(f"Measurement {i + 1} of 100:")
            i += 1
            data_printout(data)
            time.sleep(5.0)
        except KeyboardInterrupt:
            print("Measurement stopped by user.")
            break

    stop_sensor(sensor, i2c_transceiver)
    print("Measurement stopped.")


###################################
    # parser = argparse.ArgumentParser()
    # parser.add_argument('--i2c-port', '-p', default='/dev/i2c-1')
    # args = parser.parse_args()

    # with LinuxI2cTransceiver(args.i2c_port) as i2c_transceiver:
    #     channel = I2cChannel(I2cConnection(i2c_transceiver),
    #                         slave_address=0x6B,
    #                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    #     sensor = Sen66Device(channel)
    #     sensor.device_reset()
    #     time.sleep(1.2)
    #     serial_number = sensor.get_serial_number()
    #     print(f"serial_number: {serial_number}; "
    #         )
    #     sensor.start_continuous_measurement()
    #     time.sleep(30.0)
    #     for i in range(100):
    #         try:
    #             time.sleep(5.0)
    #             (mass_concentration_pm1p0, mass_concentration_pm2p5, mass_concentration_pm4p0, mass_concentration_pm10p0, humidity,
    #             temperature, voc_index, nox_index, co2
    #             ) = sensor.read_measured_values()
    #             print(f"mass_concentration_pm1p0: {mass_concentration_pm1p0}; "
    #                 f"mass_concentration_pm2p5: {mass_concentration_pm2p5}; "
    #                 f"mass_concentration_pm4p0: {mass_concentration_pm4p0}; "
    #                 f"mass_concentration_pm10p0: {mass_concentration_pm10p0}; "
    #                 f"humidity: {humidity}; "
    #                 f"temperature: {temperature}; "
    #                 f"voc_index: {voc_index}; "
    #                 f"nox_index: {nox_index}; "
    #                 f"co2: {co2}; "
    #                 )
    #         except KeyboardInterrupt:
    #             print("Measurement stopped by user.")
    #             break
    #         except Exception as e:
    #             print(f"Error during measurement: {e}")
    #             continue
    #     sensor.stop_measurement()
    #     print("Measurement stopped.")
